name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v2
    - uses: php-actions/phpunit@v9
      with:
        action_bootstrap: vendor/autoload.php
        action_args: tests
